[#116] Supports GHC 9.6.1
chshersh/iris pull request #121
Opened 2023-04-10 12:19 UTC by celsobonutti

Resolves #116

Supports GHC 9.6.1 and updates tested GHC 9.2.5 to 9.2.7.

### Additional tasks

- [ ] Documentation for changes provided/changed (N/A)
- [ ] Tests added (N/A)
- [X] Updated CHANGELOG.md

2023-04-12 22:15 UTC, chshersh requested changes
Everything looks great!

Also nice to see that CI is successfully passing, and no code changes are required 🚀 

I have a few minor suggestions but overall it looks nice 👌🏻

2023-04-12 22:15 UTC, chshersh commented on iris.cabal
> +  build-depends:       base >= 4.14 && < 4.19
Let's actually bump the upper bound to `< 5`.
```suggestion
  build-depends:       base >= 4.14 && < 5
```

I actually wrote a blog post about this recently 😅 

* https://dev.to/chshersh/new-oss-rule-do-as-little-work-as-possible-4j2k

2023-04-12 22:15 UTC, chshersh commented on CHANGELOG.md
> +  (by [@celsobonutti])
Minor formatting changes.

Also, could you please your GitHub username to the `<!-- Contributors -->` section further below in this file?

```suggestion
* [#116](https://github.com/chshersh/iris/issues/116):
  Supports GHC 9.6.1
  (by [@celsobonutti])
```

2023-04-12 22:15 UTC, chshersh commented on examples/simple-grep/simple-grep.cabal
> +  build-depends:       base >= 4.14 && < 4.19
And here too
```suggestion
  build-depends:       base >= 4.14 && < 5
```

2023-04-14 00:53 UTC, celsobonutti commented
Feedback applied! I'll take a look at the blog post 😊

2023-04-14 22:31 UTC, chshersh approved these changes
Thanks a lot! Looks perfect 🤌

2023-04-14 22:31 UTC, merged