Created Pull Request Template
chshersh/iris pull request #76
Opened 2022-10-03 11:45 UTC by Himanshu664

Created Pull Request Template
#74

2022-10-03 18:41 UTC, chshersh approved these changes
Thanks for solving this so quickly! 👏🏻

2022-10-03 18:42 UTC, chshersh requested changes
Ah, Sorry, just noticed, that the file should be inside the `.github` directory and named `PULL_REQUEST_TEMPLATE.md` instead of top-level `Pull Request Template.md`

2022-10-04 02:42 UTC, Himanshu664 commented
@chshersh Changed Directory and name you can merge this PR

2022-10-06 22:22 UTC, chshersh approved these changes
Thanks! All good now 🙂

2022-10-06 22:23 UTC, merged