[#84] Add support for GHC 9.4.2
chshersh/iris pull request #85
Opened 2022-10-07 05:42 UTC by german1608

Resolves #84

Adds support for GHC 9.4.2. Additionally, the `colourista` package declaration was updated so for cabal installs it uses the new hackage version (0.1.0.2) which supports 9.2.4, and also has a convenient base bound. For `stack`, I couldn't find a stackage for it, so I just pinned the commit from https://github.com/kowainik/colourista/commit/c7b06816ab85c27439fa7afbe6d5eed0506dd884

I also added Cabal 3.8 and GHC 9.4.2 to the build matrix for the cabal job. Let me know if we can just replace the existing cabal 3.6 with 3.8, or if it's okay to use both.

### Additional tasks

- [x] Documentation for changes provided/changed: Not needed
- [x] Tests added: Existing tests suffice.
- [x] Updated CHANGELOG.md: Should I do this?

2022-10-07 05:43 UTC, german1608 commented
Workflow execution sample on my fork: https://github.com/german1608/iris/actions/runs/3202513553

2022-10-07 09:32 UTC, chshersh requested changes
Thanks for improving this! I'm glad to see that not many code or dependency changes were required 🙂 

Only a few things left to improve and it's good to go 🚢

2022-10-07 09:32 UTC, chshersh commented on .github/workflows/ci.yml
> +        cabal: ["3.6", "3.8"]
We don't need to build with multiple `cabal` versions and display cabal in the job name. It's okay to use only the latest `cabal` version 👍🏻 

There's might be a reason not to do it when it doesn't work. But I expect things to be fine here.

2022-10-07 09:32 UTC, chshersh commented on iris.cabal
>    ghc-options:         -Wall
Let's also add the `-Wredundant-strictness-flags` flag as shown on the screenshot below for GHC 9.4. This is a new GHC sanity-check not enabled by default or by `-Wall` which I still find useful 🙂 

![image](https://user-images.githubusercontent.com/4276606/194521654-476c7c72-3a60-4f20-b0db-d492d87711c6.png)

2022-10-07 09:32 UTC, chshersh commented on stack.yaml
> +    commit: c7b06816ab85c27439fa7afbe6d5eed0506dd884
I don't think we need to depend on a GitHub commit and we can use the version from Hackage instead:

```yaml
- colourista-0.1.0.2
```

2022-10-07 09:32 UTC, chshersh commented on iris.cabal
>  common common-options
Let's also update `tested-with`

2022-10-08 13:25 UTC, chshersh approved these changes
Perfect 🔝

2022-10-08 13:40 UTC, merged